server:
  address: localhost
  port: 8080
  servlet:
    encoding:
      # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
      charset: UTF-8
      # Enable http encoding support.
      enabled: true
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true

spa:
  defalut-file: /static/index.html

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pairplay?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false
    hikari:
      username: root
      password: 1234
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: false
        format_sql: true
        ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher # springboot 2.6 version swagger 3.0.0 version error

springfox:
  documentation:
    swagger:
      use-model-v3: false

jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1296000000

spring.main.allow-bean-definition-overriding: true
